apiVersion: v1
kind: Pod
metadata:
  name: kubek-labeled
  labels:
    creation_method: manual
    env: dev  
spec:
  containers:
  - image: jagin/kubek
    name: kubek
    ports:
    - containerPort: 8000
