apiVersion: v1
kind: ReplicationController
metadata:
  name: kubek
spec:
  replicas: 3
  selector:
    app: kubek
  template:
    metadata:
      labels:
        app: kubek
    spec:
      containers:
      - name: kubek      
        image: jagin/kubek
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /health-check
            port: 8000
          initialDelaySeconds: 5
        readinessProbe:
          exec:
            command:
            - ls
            - /var/ready