apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kubek
spec:
  replicas: 3
  minReadySeconds: 15
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: kubek
      labels:
        app: kubek
    spec:
      containers:
      - image: jagin/kubek:v3
        name: kubek
        readinessProbe:
          periodSeconds: 1
          httpGet:
            path: /
            port: 8000
