apiVersion: v1
kind: Pod
metadata:
  name: kubek
spec:
  containers:
  - image: jagin/kubek
    env:
    - name: AUTH_USER
      valueFrom:
        secretKeyRef:
          name: kubek-secret
          key: user
    - name: AUTH_PASSWORD
      valueFrom:
        secretKeyRef:
          name: kubek-secret
          key: password           
    name: kubek
    ports:
    - containerPort: 8000

