apiVersion: v1
kind: Pod
metadata:
  name: kubek
spec:
  containers:
  - image: jagin/kubek
    name: kubek
    volumeMounts:
    - name: config
      mountPath: /app/public
      readOnly: true
    ports:
    - containerPort: 8000
  volumes:
  - name: config
    configMap:
      name: kubek-config
