apiVersion: v1
kind: Pod
metadata:
  name: kubek
spec:
  containers:
  - image: jagin/kubek
    name: kubek
    ports:
    - name: http
      containerPort: 8000
    - name: https
      containerPort: 8443
